name: push-pipeline
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  image-build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: login to GitHub Container Registry
        run: echo ${{ secrets.DPASS }} | docker login -u ${{ secrets.DNAME }} --password-stdin

      - name: Build & Push Docker Image
        env:
          DNAME: ${{ secrets.DNAME }}
          DPASS: ${{ secrets.DPASS }}
        run: |
          docker build --file Dockerfile --tag uditgaurav/mssql:load .
          docker push uditgaurav/mssql:load